config/routes.rb
Rails.application.routes.draw do
   devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

    root "events#index"

    resources :events do
      get :balance, on: :collection
    end

    resources :users do
      post :add_transction, on: :collection
      put :add_friend, on: :collection
      get :get_friends, on: :collection
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps


  #attributes

  field :name, type: String
  field :location, type: String
  field :total_amount, type: Float
  field :date,  type: Date
  field :user_ids, type: Array, default: []

  #associations


  has_and_belongs_to_many :users
  has_many :payments


  def create_payments(params)
    params.each  do |count,payment_hash|
        self.payments.create(user_id:payment_hash[:user],amount:payment_hash[:amount])
    end

  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_user

  def index
    @events = Event.all
    respond_to do |format|
      format.html { render :index}
    end
  end


  def create
    event_params = filter_params
    payments = params[:event][:payment]

    event = Event.create(event_params)
    event.create_payments(payments)

    respond_to do |format|

    end

  end

  def balance
    @friend_balance_sheet = @user.get_balance_sheet
  end

  def update
  end

  def filter_params
    params.require(:event).permit(:name, :location, :total_amount, :user_ids => [])
  end

end

app/views/events/balance.html.erb
<div class="row">
  <div class="panel">
    <div class="panel-heading">
      <h3 class="panel-title"> Balance Sheet </h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <table class="table table-bordered text-center">
          <tr>
            <th> Name </th>
            <th> Total Amount </th>
          </tr>
          <% @friend_balance_sheet.each do |id, balance| %>
            <tr>
              <td> <%= User.find(id).name %> </td>
              <td>
                <% if (balance < 0) %>
                  <% css_class = 'text-danger' %>
                <% else %>
                  <% css_class = 'text-success' %>
                <% end %>
                <p class="<%= css_class%>"> <b> <%= balance %> </b> </p>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <hr>
      <div class="row text-center">
        <h4>Make Transcation</h4>
        <form method="post" action="<%= add_transction_users_path %>">
          <select id="payer" name="payer">
            <option></option>
          </select>
          <select id="payee" name="payee">
            <option></option>
          </select>
          <input  type="number" name="amount">
          <button class="btn btn-submit"> Make Payment </button>
        </form>
      </div>

    </div>
  </div>
</div>


<%= javascript_tag do %>
  $(function(){
    Balance.initialize();
  });
<% end %>

app/views/events/index.html.erb
<div class = "col-lg-9">
  <label class="label"> Previous Events </label>
  <div>
    <table class="table">
      <tr>
        <th>Event Name</th>
        <th>Location</th>
        <th>Total Amount</th>
        <th>Members</th>
      </tr>
      <% @events.each do |event| %>
        <tr>
          <td><%=  event.name %></td>
          <td><%=  event.location %></td>
          <td><%=  event.total_amount %></td>
          <td>Members</td>
        </tr>

      <% end %>
    </table>
  </div>


</div>
<div class="col-lg-3">
  <form class="form">
  <div class="panel">
  <div class="panel-heading">
    <div class="panel-title">
      <h4 class=> Create event </h4>
    </div>
  </div>
  <div class="panel-body">
    <label>Name</label>
    <input  class= "form-control" name="event[name]"></input>
    <label>Location</label>
    <input   class= "form-control" name="event[location]"></input>
    <label>Members</label>
    <select multiple="multiple" id="event-member" class="form-control" name="event[user_ids][]"> </select>
    <label>Total Amount</label>
    <input  type="number" class= "form-control" name="event[total_amount]"></input>
  </div>
  <label>Payments</label>
  <div class="btn add-payment btn-default fa fa-plus">Add Payment</div>
    <div id="payments"> </div>
      <div>
        <div class="btn btn-primary pull-right" id="create-event"> Create</div>
      </div>
    </form>
</div>

<%= javascript_tag do %>
  $(function(){
    Events.initialize();
  });
<% end %>