config/routes.rb
Rails.application.routes.draw do
   devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

    root "events#index"

    resources :events do
      get :balance, on: :collection
    end

    resources :users do
      post :add_transction, on: :collection
      put :add_friend, on: :collection
      get :get_friends, on: :collection
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand">Split Easy</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <%- if signed_in? %>
        <li><a href="/events">Events</a></li>
        <li><%= link_to 'Balance', balance_events_path %></li>
        <li><%= link_to 'Profile', user_path(@user.id) %></li>
        <%- end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%- if signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: "delete" %></li>
        <%- else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <%- end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Split Easy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:error_message].present? %>
    <div class="alert alert-danger"><%= flash[:error_message] %></div>
<%elsif flash[:success_message].present?%>
  <div class="alert alert-success"><%= flash[:success_message] %></div>
<% end %>
<%=render partial:"layouts/navbar" %>
<%= yield %>

</body>
</html>